using Ses.Core;
using System.Text;

int checks = 0, failures = 0;
void Check(string name, Action test) { checks++; try { test(); Console.WriteLine("PASS " + name); } catch (Exception ex) { failures++; Console.WriteLine("FAIL " + name + ": " + ex.Message); } }
void Assert(bool value) { if (!value) throw new Exception("assertion failed"); }
void Reject(Action test) { try { test(); } catch (InvalidDataException) { return; } throw new Exception("invalid input accepted"); }
Check("Veylo accepts legacy startup targets without accepting arbitrary executables",()=>{
    const string legacy="\"C:\\Old\\SES.exe\" --minimized";
    const string current=@"C:\Apps\Veylo\Veylo.exe";
    Assert(StartupRegistration.TryGetTarget("\""+current+"\" --minimized",out string target)&&target==current);
    Assert(StartupRegistration.TryUpgrade(legacy,current,new(0,6,11),new(0,6,12))=="\""+current+"\" --minimized");
    Assert(StartupRegistration.TryUpgrade("\""+current+"\" --minimized",@"C:\Old\SES.exe",new(0,6,12),new(0,6,11)) is null);
    foreach(string executable in new[]{@"C:\Apps\Veylo.exe.bat",@"C:\Apps\other.exe",@"\\server\share\Veylo.exe",@"C:\Apps\Veylo.exe:payload"})
        Assert(!StartupRegistration.TryGetTarget("\""+executable+"\" --minimized",out _));
});
Check("startup upgrade recognizes only the exact enabled local SES command",()=>{
    const string path=@"C:\Program Files\SES 0.1.0\SES.exe";
    Assert(StartupRegistration.TryGetTarget("\""+path+"\" --minimized",out string target)&&target==path);
    foreach(string? command in new string?[]{null,"","\"","\" --minimized","\"\" --minimized","SES.exe --minimized",path+" --minimized","\""+path+"\"", "\""+path+"\" --minimized --other","\""+path+"\"  --minimized"," \""+path+"\" --minimized","\""+path+"\" --minimized\n","\"C:\\other.exe\" --minimized","\"relative\\SES.exe\" --minimized"}){
        Assert(!StartupRegistration.TryGetTarget(command,out target)&&target=="");
        Assert(StartupRegistration.TryUpgrade(command,@"C:\Current\SES.exe",new(0,1,0),new(0,6,8)) is null);
    }
});
Check("startup upgrade rejects unsafe Windows targets before metadata lookup",()=>{
    foreach(string path in new[]{@"\\server\share\SES.exe",@"\\?\C:\SES.exe",@"C:SES.exe",@"C:\Old\..\SES.exe",@"C:\.\SES.exe",@"C:\Old.\SES.exe",@"C:\Old \SES.exe",@"C:\Old\\SES.exe",@"C:\Old\SES.exe:payload",@"C:/Old/SES.exe","C:\\Old\n\\SES.exe","C:\\Old\"\\SES.exe",@"C:\Old*\SES.exe",@"C:\Old|\SES.exe",@"C:\Old?\SES.exe"}){
        Assert(!StartupRegistration.TryGetTarget("\""+path+"\" --minimized",out _));
        Assert(StartupRegistration.TryUpgrade("\"C:\\Old\\SES.exe\" --minimized",path,new(0,1,0),new(0,6,8)) is null);
    }
});
Check("startup upgrade preserves absence and unknown versions",()=>{
    const string saved="\"C:\\Old\\SES.exe\" --minimized";
    Assert(StartupRegistration.TryUpgrade(saved,@"C:\Current\SES.exe",null,new(0,6,8)) is null);
    Assert(StartupRegistration.TryUpgrade(saved,@"C:\Current\SES.exe",new(0,1,0),null) is null);
    Assert(StartupRegistration.TryUpgrade(saved,null!,new(0,1,0),new(0,6,8)) is null);
});
Check("startup upgrade selects newer explicitly launched SES without downgrading",()=>{
    const string saved="\"C:\\Old\\SES.exe\" --minimized";const string current=@"D:\Apps\SES 0.6.8\SES.exe";
    foreach(var old in new[]{new Version(0,1,0),new Version(0,6,0),new Version(0,6,7),new Version(0,6,8),new Version(0,6,8,0)})
        Assert(StartupRegistration.TryUpgrade(saved,current,old,new(0,6,8))=="\""+current+"\" --minimized");
    foreach(var old in new[]{new Version(0,6,8,1),new Version(0,6,9),new Version(1,0)})
        Assert(StartupRegistration.TryUpgrade(saved,current,old,new(0,6,8)) is null);
    Assert(StartupRegistration.TryUpgrade(saved,@"c:\old\ses.EXE",new(0,1,0),new(0,6,8)) is null);
});
Check("live validation defaults and explicit one-hour cable run",()=>{Assert(LiveValidationOptions.Parse([])==new LiveValidationOptions(30,false));Assert(LiveValidationOptions.Parse(["--validate-cable","--validate-duration-seconds","3600"])==new LiveValidationOptions(3600,true));Assert(LiveValidationOptions.Parse(["--validate-duration-seconds","1"]).DurationSeconds==1);});
Check("live validation rejects missing duplicate unbounded and malformed durations",()=>{foreach(string bad in new[]{"0","3601","-1","+30","1.5","NaN","2147483648",""})Reject(()=>LiveValidationOptions.Parse(["--validate-duration-seconds",bad]));Reject(()=>LiveValidationOptions.Parse(["--validate-duration-seconds"]));Reject(()=>LiveValidationOptions.Parse(["--validate-duration-seconds","30","--validate-duration-seconds","60"]));});
Check("live validation low overhead preserves bounded duration and cable options",()=>{
    Assert(LiveValidationOptions.Parse(["--validate-live","--validate-low-overhead"])==new LiveValidationOptions(30,false,true));
    foreach(string duration in new[]{"1","3600"}){
        var options=LiveValidationOptions.Parse(["--validate-low-overhead","--validate-duration-seconds",duration,"--validate-cable","--validate-live"]);
        Assert(options==new LiveValidationOptions(int.Parse(duration),true,true));
    }
    foreach(string duration in new[]{"0","3601","-1","+30","1.5","NaN","2147483648",""})
        Reject(()=>LiveValidationOptions.Parse(["--validate-live","--validate-low-overhead","--validate-duration-seconds",duration]));
});
Check("live validation diagnostic cadence derives only from low overhead mode",()=>{
    var normal=new LiveValidationOptions(30,false);var low=normal with{LowOverhead=true};
    Assert(!normal.LowOverhead&&normal.PollIntervalMilliseconds==100&&normal.ProgressIntervalSeconds==10);
    Assert(low.PollIntervalMilliseconds==1000&&low.ProgressIntervalSeconds==30);
    Assert(LiveValidationOptions.Parse(["--validate-live"])==normal);
});
Check("live validation low overhead requires explicit live mode and cannot repeat",()=>{
    foreach(string[] args in new string[][]{
        ["--validate-low-overhead"],
        ["--smoke","--validate-low-overhead"],
        ["--validate-duration-seconds","1","--validate-low-overhead"],
        ["--validate-cable","--validate-low-overhead"],
        ["--validate-live","--validate-low-overhead","--validate-low-overhead"],
        ["--validate-low-overhead","--validate-live","--validate-low-overhead"]})
        Reject(()=>LiveValidationOptions.Parse(args));
});
Check("live timing percentiles expose overflow instead of underreporting slow blocks",()=>{var h=new SampledTimingHistogram();Assert(h.PercentileUpperBound(.95) is null);for(int i=0;i<90;i++)h.Record(.05);for(int i=0;i<10;i++)h.Record(20);Assert(h.Count==100&&h.OverflowCount==10&&h.PercentileUpperBound(.5) is >.05 and <=.06&&h.PercentileUpperBound(.95) is null&&h.PercentileUpperBound(.99) is null);Reject(()=>h.Record(double.NaN));Reject(()=>h.Record(-1));});
Check("live final snapshot rejects reset disconnected route change and broken mute",()=>{var m=new EngineMetrics{Running=1,Connected=1,OutputKind=2,ProcessedFrames=2000,OutputDb=-120};Assert(LiveStreamChecks.IsContinuous(m,1000,2,true));m.ProcessedFrames=1;Assert(!LiveStreamChecks.IsContinuous(m,1000,2,true));m.ProcessedFrames=2000;m.Connected=0;Assert(!LiveStreamChecks.IsContinuous(m,1000,2,true));m.Connected=1;Assert(!LiveStreamChecks.IsContinuous(m,1000,1,true)&&!LiveStreamChecks.IsContinuous(m,1000,2,false));m.OutputDb=float.NaN;Assert(!LiveStreamChecks.IsContinuous(m,1000,2,true));});
Check("live acceptance fails CPU and decimal memory budget overruns",()=>{Assert(LiveStreamChecks.MeetsResourceTargets(3,150_000_000));foreach(double cpu in new[]{-1d,3.01,double.NaN,double.PositiveInfinity})Assert(!LiveStreamChecks.MeetsResourceTargets(cpu,140_000_000));Assert(!LiveStreamChecks.MeetsResourceTargets(1,150_000_001)&&!LiveStreamChecks.MeetsResourceTargets(1,0));});
Check("five factory profiles are independently editable", () => { var a=Profiles.Factory(); var b=Profiles.Factory(); Assert(a.Count==5); a[0].Settings.Bands[0].GainDb=7; Assert(b[0].Settings.Bands[0].GainDb==0); });
Check("sensitivity roundtrip retains manual threshold and automatic mode independently",()=>{var p=Profiles.Factory()[0];p.Settings.SensitivityEnabled=true;p.Settings.SensitivityAutoEnabled=true;p.Settings.SensitivityThresholdDb=-57;var copy=Profiles.Deserialize(Profiles.Serialize(p));Assert(copy.Settings.SensitivityEnabled&&copy.Settings.SensitivityAutoEnabled&&copy.Settings.SensitivityThresholdDb==-57);});
Check("legacy presets do not silently introduce sensitivity control",()=>{var p=Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"Old\",\"settings\":{}}");Assert(!p.Settings.SensitivityEnabled&&p.Settings.SensitivityAutoEnabled&&p.Settings.SensitivityThresholdDb==-50);});
Check("sensitivity rejects invalid and nonfinite thresholds",()=>{Reject(()=>new AudioSettings{SensitivityThresholdDb=-91}.Validate());Reject(()=>new AudioSettings{SensitivityThresholdDb=float.NaN}.Validate());});
Check("automatic noise mode roundtrips without changing manual strength",()=>{var p=Profiles.Factory()[0];p.Settings.NoiseAutoEnabled=true;p.Settings.NoiseMix=.31f;var copy=Profiles.Deserialize(Profiles.Serialize(p));Assert(copy.Settings.NoiseAutoEnabled&&copy.Settings.NoiseMix==.31f);});
Check("old presets retain manual noise behavior",()=>{var p=Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"Legacy\",\"settings\":{\"noiseMix\":0.42}}");Assert(!p.Settings.NoiseAutoEnabled&&p.Settings.NoiseMix==.42f);});
Check("shared preset contains no local device state", () => { var text=Profiles.Serialize(Profiles.Factory()[0]); Assert(!text.Contains("device",StringComparison.OrdinalIgnoreCase)); Assert(Profiles.Deserialize(text).Settings.HighpassHz==80); });
Check("reject unsupported profile version", () => Reject(()=>Profiles.Deserialize("{\"schemaVersion\":999,\"name\":\"x\",\"settings\":{}}")));
Check("reject incomplete profile", () => Reject(()=>Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"x\"}")));
Check("reject oversized profile", () => Reject(()=>Profiles.Deserialize(new string(' ',65537))));
Check("reject malformed JSON", () => Reject(()=>Profiles.Deserialize("{broken")));
Check("reject null and duplicate preset settings", () => { Reject(()=>Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"x\",\"settings\":null}"));Reject(()=>Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"x\",\"settings\":{},\"settings\":{}}")); });
Check("local null profile recovers safely",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"{\"Profiles\":[null]}");var store=new UserStore(root);Assert(store.Load().Profiles.Count==0&&store.LoadWarning);}finally{Directory.Delete(root,true);}});
Check("reject unsafe gain", () => { var p=Profiles.Factory()[0]; p.Settings.MaxGainDb=100; Reject(()=>Profiles.Serialize(p)); });
Check("reject non-finite frequency", () => { var p=Profiles.Factory()[0]; p.Settings.Bands[0].Frequency=float.NaN; Reject(()=>Profiles.Serialize(p)); });
Check("invalid edited settings clone fails as validation error",()=>{var s=new AudioSettings();s.Bands[0].Frequency=float.NaN;Reject(()=>s.Clone());});
Check("comparison removes actual RNNoise delay",()=>{var raw=new float[5000];raw[1000]=.1f;var processed=new float[5000];processed[1960]=.1f;var matched=AudioSamples.Match(raw,processed);Assert(matched.Raw.Length==4040&&matched.Raw[1000]==matched.Processed[1000]);});
Check("reject invalid EQ band count", () => { var p=Profiles.Factory()[0]; p.Settings.Bands=[]; Reject(()=>Profiles.Serialize(p)); });
Check("level matching cannot clip or inflate silence", () => { var a=Enumerable.Repeat(.5f,48000).ToArray();var b=Enumerable.Repeat(.1f,48000).ToArray();var pair=AudioSamples.Match(a,b);Assert(Math.Abs(pair.Raw[100]-pair.Processed[100])<.001f);Assert(pair.Raw.Max()<.891252f);var zero=AudioSamples.Match(new float[1000],new float[1000]);Assert(zero.Raw.All(x=>x==0)); });
Check("WAV encoding is bounded PCM", () => { var bytes=AudioSamples.Wave([float.NaN,4,-4,0]); Assert(Encoding.ASCII.GetString(bytes,0,4)=="RIFF");Assert(bytes.Length==52); Assert(BitConverter.ToInt16(bytes,46)==32767); });
Check("calibration rejects clipped input", () => { var x=new float[720000];for(int i=240000;i<x.Length;i++)x[i]=1;Assert(!Calibration.Analyze(x).Success); });
Check("calibration rejects silence", () => Assert(!Calibration.Analyze(new float[720000]).Success));
Check("calibration accepts adequate speech", () => { var x=new float[720000];for(int i=240000;i<x.Length;i++)x[i]=.1f*(float)Math.Sin(i*.025);var r=Calibration.Analyze(x);Assert(r.Success);Assert(r.NoiseFloorDb<=-60);Assert(Math.Abs(r.SpeechDb+23)<2); });
float[] PersonalSample(float amplitude=.08f,float ambient=.0005f,float bass=1)
{
    var data=new float[AudioSamples.MaxFrames];var random=new Random(83);
    for(int i=0;i<data.Length;i++){
        double seconds=i/(double)AudioSamples.Rate;
        float level=seconds<5?0:seconds<12?amplitude:seconds<16?amplitude*.45f:amplitude*1.8f;
        double voice=bass*Math.Sin(i*2*Math.PI*170/48000)+.35*Math.Sin(i*2*Math.PI*900/48000)+.18*Math.Sin(i*2*Math.PI*2800/48000);
        data[i]=level*(float)voice+ambient*(float)(random.NextDouble()-.5);
    }
    return data;
}
Check("personal calibration tailors gain limits to quieter microphones",()=>{var quiet=PersonalCalibration.Analyze(PersonalSample(.015f));var loud=PersonalCalibration.Analyze(PersonalSample(.15f));Assert(quiet.Success&&loud.Success);Assert(quiet.Settings!.MaxGainDb>loud.Settings!.MaxGainDb);Assert(quiet.Settings.TargetDb==-20&&quiet.Settings.OutputDb==0);});
Check("personal calibration responds to ambient noise and remains conservative",()=>{var quiet=PersonalCalibration.Analyze(PersonalSample());var noisy=PersonalCalibration.Analyze(PersonalSample(.08f,.012f));Assert(quiet.Success&&noisy.Success);Assert(noisy.Settings!.NoiseMix>quiet.Settings!.NoiseMix);Assert(noisy.Settings.NoiseAutoEnabled&&noisy.Settings.Bands.All(b=>Math.Abs(b.GainDb)<=2));noisy.Settings.Validate();});
Check("personal calibration rejects incomplete, invalid and clipped samples",()=>{Assert(!PersonalCalibration.Analyze(new float[479]).Success);Assert(!PersonalCalibration.Analyze(new float[AudioSamples.MaxFrames+1]).Success);var x=PersonalSample();x[77]=float.NaN;Assert(!PersonalCalibration.Analyze(x).Success);x=PersonalSample();for(int i=0;i<40;i++)x[300000+i]=1;Assert(PersonalCalibration.Analyze(x).Error=="calibrationClipped");});
Check("personal calibration requires speech in every prompted section",()=>{var x=PersonalSample();Array.Clear(x,12*48000,4*48000);Assert(PersonalCalibration.Analyze(x).Error=="autoQuietMissing");x=PersonalSample();Array.Clear(x,16*48000,4*48000);Assert(PersonalCalibration.Analyze(x).Error=="autoLoudMissing");Assert(!PersonalCalibration.Analyze(new float[AudioSamples.MaxFrames]).Success);});
Check("personal calibration rejects constant DC as speech",()=>Assert(!PersonalCalibration.Analyze(Enumerable.Repeat(.08f,AudioSamples.MaxFrames).ToArray()).Success));
Check("personal calibration rejects contaminated ambient sample",()=>{var x=PersonalSample();var normal=x.AsSpan(5*48000,5*48000).ToArray();normal.CopyTo(x,0);Assert(!PersonalCalibration.Analyze(x).Success);});
Check("personal calibration stage boundaries are deterministic",()=>{Assert(PersonalCalibration.StageKey(0)=="autoAmbient");Assert(PersonalCalibration.StageKey(5*48000)=="autoNormal");Assert(PersonalCalibration.StageKey(12*48000)=="autoQuiet");Assert(PersonalCalibration.StageKey(16*48000)=="autoLoud");});
Check("personal calibration speech verification rejects louder non-speech",()=>{var result=PersonalCalibration.Analyze(PersonalSample());Assert(result.Success);Assert(!PersonalCalibration.VerifySpeech(result,new float[2000]).Success);var activity=new float[2000];Array.Fill(activity,.8f,500,1500);Assert(PersonalCalibration.VerifySpeech(result,activity).Success);Array.Fill(activity,0,1200,400);Assert(PersonalCalibration.VerifySpeech(result,activity).Error=="autoQuietMissing");});
Check("personal calibration apply and undo preserve unrelated device state",()=>{var state=new UserState{InputId="mic-A",OutputId="cable"};state.Calibrations["mic-B"]=new(-64,-22,DateTimeOffset.UnixEpoch);float oldMix=state.Settings.NoiseMix;var change=PersonalCalibrationChange.Apply(state,"mic-A",PersonalCalibration.Analyze(PersonalSample()),"Personal voice");Assert(state.Settings.NoiseAutoEnabled&&state.Calibrations["mic-A"].TunedSettings is not null);Assert(state.Profiles.Count==1&&state.OutputId=="cable");change.Undo(state);Assert(state.Profiles.Count==0&&state.Settings.NoiseMix==oldMix&&!state.Calibrations.ContainsKey("mic-A")&&state.Calibrations["mic-B"].NoiseFloorDb==-64);});
Check("personal calibration cannot apply to a changed input or failed result",()=>{var state=new UserState{InputId="mic-B"};Reject(()=>PersonalCalibrationChange.Apply(state,"mic-A",PersonalCalibration.Analyze(PersonalSample()),"Personal"));Assert(state.Profiles.Count==0);Reject(()=>PersonalCalibrationChange.Apply(state,"mic-B",PersonalCalibration.Analyze(new float[20]),"Personal"));});
Check("personal calibration limit fails before changing settings",()=>{var state=new UserState{InputId="mic"};for(int i=0;i<100;i++)state.Profiles.Add(new(){Name="Profile "+i});Reject(()=>PersonalCalibrationChange.Apply(state,"mic",PersonalCalibration.Analyze(PersonalSample()),"Personal"));Assert(!state.Settings.NoiseAutoEnabled&&state.Calibrations.Count==0);});
Check("saved personal calibration retains per-device settings without voice",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);var state=new UserState{InputId="local-microphone"};PersonalCalibrationChange.Apply(state,state.InputId,PersonalCalibration.Analyze(PersonalSample()),"Personal");store.Save(state);var saved=store.Load();Assert(saved.Calibrations[state.InputId].TunedSettings!.NoiseAutoEnabled);string shared=Profiles.Serialize(saved.Profiles[0]);Assert(!shared.Contains(state.InputId)&&!shared.Contains("sample",StringComparison.OrdinalIgnoreCase));}finally{Directory.Delete(root,true);}});
Check("personal tone responds to spectral differences without large boosts",()=>{var full=PersonalCalibration.Analyze(PersonalSample(.04f,.0003f,2));var thin=PersonalCalibration.Analyze(PersonalSample(.04f,.0003f,.1f));Assert(full.Success&&thin.Success);Assert(!full.Settings!.Bands.Select(b=>b.GainDb).SequenceEqual(thin.Settings!.Bands.Select(b=>b.GainDb)));});
Check("personal settings remain finite across a range of microphone levels",()=>{for(int i=1;i<12;i++){var result=PersonalCalibration.Analyze(PersonalSample(.005f*i,.0001f*i,i*.2f));if(result.Success){result.Settings!.Validate();Assert(result.Settings.MaxGainDb<=12&&result.Settings.MinGainDb>=-12&&result.Settings.Bands.All(b=>b.GainDb<=1&&b.GainDb>=-2));}else Assert(result.Settings is null);}});
Check("personal undo restores an existing device calibration and avoids name collisions",()=>{var state=new UserState{InputId="mic"};var old=new DeviceCalibration(-55,-25,DateTimeOffset.UnixEpoch,new AudioSettings{HighpassHz=95});state.Calibrations["mic"]=old;state.Profiles.Add(new(){Name="Personal"});var change=PersonalCalibrationChange.Apply(state,"mic",PersonalCalibration.Analyze(PersonalSample()),"Personal");Assert(state.ActiveProfile=="user:Personal 2");change.Undo(state);Assert(state.Profiles.Count==1&&state.Calibrations["mic"].TunedSettings!.HighpassHz==95);});
Check("legacy device calibration remains loadable without personal settings",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);var state=new UserState();state.Calibrations["mic"]=new(-60,-23,DateTimeOffset.UnixEpoch);store.Save(state);var restored=store.Load();Assert(!store.LoadWarning&&restored.Calibrations["mic"].TunedSettings is null);}finally{Directory.Delete(root,true);}});
Check("corrupt saved personal settings are rejected at the local state boundary",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{Directory.CreateDirectory(root);var state=new UserState();state.Calibrations["mic"]=new(-60,-23,DateTimeOffset.UnixEpoch,new AudioSettings{MaxGainDb=500});File.WriteAllText(Path.Combine(root,"state.json"),System.Text.Json.JsonSerializer.Serialize(state));var store=new UserStore(root);Assert(store.Load().Calibrations.Count==0&&store.LoadWarning);}finally{Directory.Delete(root,true);}});
Check("local state roundtrip retains device calibration",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);var state=new UserState();state.Calibrations["test-device"]=new(-65,-23,DateTimeOffset.UnixEpoch);store.Save(state);Assert(store.Load().Calibrations["test-device"].NoiseFloorDb==-65);}finally{Directory.Delete(root,true);}});
Check("corrupt local state recovers without overwriting original",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"broken");var store=new UserStore(root);Assert(store.Load().Settings.TargetDb==-20&&store.LoadWarning);Assert(File.ReadAllText(Path.Combine(root,"state.json"))=="broken");}finally{Directory.Delete(root,true);}});
if(args.Length>0) {
Check("first run prefers a physical microphone over default cable",()=>{AudioDevice[] devices=[new("cable","CABLE Output (VB-Audio Virtual Cable)",true,true),new("ses","SES Mikrofon",true,false,true),new("usb","USB microphone",true,false)];Assert(InputSelection.Choose(devices,"")?.Id=="usb");Assert(InputSelection.Choose(devices,"missing") is null);Assert(InputSelection.Choose(devices,"ses") is null);Assert(InputSelection.Choose(devices,"cable")?.Id=="cable");});
Check("valid Windows default physical microphone is honored",()=>Assert(InputSelection.Choose([new("a","Microphone A",true,false),new("b","Microphone B",true,true)],"")?.Id=="b"));
using var engine=new NativeEngine(args[0]);
Check("optional stream diagnostics preserve ABI5 and expose no offline callbacks",()=>{var diagnostic=engine.Diagnostics();Assert(diagnostic is {Version:1,Size:96,CaptureCallbacks:0,PlaybackCallbacks:0});Assert(System.Runtime.InteropServices.Marshal.SizeOf<EngineMetrics>()==136&&System.Runtime.InteropServices.Marshal.SizeOf<StreamDiagnostics>()==96);});
var endpoints=engine.Devices();
Check("native wrapper enumerates bounded endpoint metadata",()=>Assert(endpoints.Count<=128&&endpoints.All(d=>d.Id.Length is >0 and <512&&d.Name.Length<256)));
if(endpoints.Any(d=>d.Input)||!args.Skip(1).Contains("--allow-no-audio-device",StringComparer.Ordinal))
    Check("native wrapper finds an actual capture endpoint",()=>Assert(endpoints.Any(d=>d.Input)));
else Console.WriteLine("SKIP physical capture endpoint availability: explicitly requested headless host; enumeration API was checked above.");
Check("podcast chain reduces stationary room sample and safely handles level bursts",()=>{var podcast=Profiles.Factory().Single(p=>p.FactoryId=="podcast").Settings;var random=new Random(93);var room=Enumerable.Range(0,48000*3).Select(_=>(float)(random.NextDouble()-.5)*.003f).ToArray();using var p=new NativeEngine(args[0]);using var n=new NativeEngine(args[0]);var clean=p.Process(room,podcast);var normal=n.Process(room,Profiles.Factory()[0].Settings);double Energy(float[] samples)=>samples.Skip(48000).Sum(v=>(double)v*v);Assert(Energy(clean)<Energy(normal));var voice=PersonalSample(.08f);for(int i=790000;i<790480;i++)voice[i]*=12;var output=p.Process(voice,podcast);Assert(output.Length==voice.Length&&output.All(v=>float.IsFinite(v)&&Math.Abs(v)<=.891252f));});
Check("native sensitivity flags threshold and gain cross ABI correctly",()=>{using var sensitivity=new NativeEngine(args[0]);var input=Enumerable.Range(0,48000*2).Select(i=>.001f*(float)Math.Sin(i*.03)).ToArray();var settings=new AudioSettings{NoiseEnabled=false,AgcEnabled=false,SensitivityEnabled=true,SensitivityAutoEnabled=false,SensitivityThresholdDb=-45};var output=sensitivity.Process(input,settings);var metrics=sensitivity.Metrics();Assert(metrics.SensitivityThresholdDb==-45&&metrics.SensitivityGain==0&&output.All(v=>v==0));settings.SensitivityAutoEnabled=true;sensitivity.Process(input,settings);Assert(sensitivity.Metrics().SensitivityThresholdDb!=-45);settings.SensitivityAutoEnabled=false;sensitivity.Process(input,settings);Assert(sensitivity.Metrics().SensitivityThresholdDb==-45);});
Check("native wrapper passes automatic mode and reads actual strength",()=>{using var automatic=new NativeEngine(args[0]);var random=new Random(53);var x=Enumerable.Range(0,48000*4).Select(_=>(float)(random.NextDouble()-.5)*.12f).ToArray();automatic.Process(x,new AudioSettings{NoiseAutoEnabled=true,AgcEnabled=false});var metrics=automatic.Metrics();Assert(metrics.NoiseMix>.65f&&metrics.NoiseMix<=.95f&&float.IsFinite(metrics.NoiseFloorDb));});
Check("offline RNNoise speech analysis is bounded and rejects silent calibration",()=>{using var offline=new NativeEngine(args[0]);var activity=offline.SpeechActivity(new float[AudioSamples.MaxFrames]);Assert(activity.Length==2000&&activity.All(p=>float.IsFinite(p)&&p>=0&&p<=1));Assert(!PersonalCalibration.VerifySpeech(PersonalCalibration.Analyze(PersonalSample()),activity).Success);});
Check("personal recommendation passes through the real native chain safely",()=>{using var offline=new NativeEngine(args[0]);var input=PersonalSample(.07f);var recommendation=PersonalCalibration.Analyze(input);Assert(recommendation.Success);var output=offline.Process(input,recommendation.Settings!,recommendation.NoiseFloorDb);Assert(output.Length==input.Length&&output.All(v=>float.IsFinite(v)&&Math.Abs(v)<=.891252f));});
Check("native wrapper preserves limiter",()=>{var x=Enumerable.Repeat(4f,48000).ToArray();var settings=new AudioSettings { NoiseEnabled=false,AgcEnabled=false,CompressorRatio=1 };var y=engine.Process(x,settings);Assert(y.All(n=>float.IsFinite(n)&&Math.Abs(n)<=.891252f));});
Check("native wrapper rejects unsafe settings",()=>Reject(()=>engine.Process(new float[480],new AudioSettings { MaxGainDb=999 })));
Check("missing saved device waits without falling back",()=>{engine.Start("nonexistent-endpoint",null);Assert(engine.Metrics().Running==1&&engine.Metrics().Connected==0);engine.Stop();});
}
Check("game mode detects a known background game case-insensitively",()=>{var p=new GameModePolicy();Assert(p.Update(true,new[]{new GameObservation("valorant-win64-shipping.exe")},Array.Empty<string>(),0));Assert(p.DetectedName=="valorant-win64-shipping");});
Check("game mode accepts custom names but excludes normal fullscreen browsers",()=>{var p=new GameModePolicy();Assert(!p.Update(true,new[]{new GameObservation("chrome",true),new GameObservation("steam",true)},Array.Empty<string>(),0));Assert(p.Update(true,new[]{new GameObservation("MyGame")},new[]{"mygame.exe"},1));});
Check("game mode fullscreen fallback and recovery hold are deterministic",()=>{var p=new GameModePolicy();Assert(p.Update(true,new[]{new GameObservation("UnknownGame",true)},Array.Empty<string>(),0));Assert(p.Update(true,Array.Empty<GameObservation>(),Array.Empty<string>(),14.9));Assert(!p.Update(true,Array.Empty<GameObservation>(),Array.Empty<string>(),15));});
Check("disabling game mode immediately clears hold and detection",()=>{var p=new GameModePolicy();p.Update(true,new[]{new GameObservation("cs2")},Array.Empty<string>(),1);Assert(!p.Update(false,new[]{new GameObservation("cs2")},Array.Empty<string>(),2)&&p.DetectedName.Length==0);});
Check("game process input rejects paths commands duplicates and excessive lists",()=>{Reject(()=>GameModePolicy.ValidateNames(new(){"../Game.exe"}));Reject(()=>GameModePolicy.ValidateNames(new(){"Game;cmd"}));Reject(()=>GameModePolicy.ValidateNames(new(){"Game", "GAME.exe"}));Reject(()=>GameModePolicy.ValidateNames(Enumerable.Range(0,21).Select(i=>"Game"+i).ToList()));Reject(()=>GameModePolicy.ValidateNames(null));GameModePolicy.ValidateNames(new(){"League of Legends.exe","javaw"});});
Check("legacy state defaults to automatic game mode without changing audio",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"{}");var s=new UserStore(root).Load();Assert(s.GameModeEnabled&&s.EffectsEnabled&&s.GameProcessNames.Count==0&&s.Settings.TargetDb==-20);}finally{Directory.Delete(root,true);}});
Check("game preferences persist locally and stay out of shared presets",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);store.Save(new UserState{GameModeEnabled=false,EffectsEnabled=false,GameProcessNames=new(){"MyGame.exe"}});var s=store.Load();Assert(!s.GameModeEnabled&&!s.EffectsEnabled&&s.GameProcessNames.Single()=="MyGame.exe");Assert(!Profiles.Serialize(Profiles.Factory()[0]).Contains("GameProcess"));}finally{Directory.Delete(root,true);}});
Check("routing exposes only cable render endpoints and explicit driver/local routes",()=>{var routes=OutputRouting.Choices([new("speaker","Speakers",false,true),new("mic","CABLE Input",true,false),new("cable","CABLE Input (VB-Audio Virtual Cable)",false,false)],"","missing","driver","local");Assert(routes.Length==3&&routes[0].Id=="cable"&&!routes.Any(r=>r.Id=="speaker"||r.Id=="mic"));Assert(OutputRouting.EffectiveKind(OutputRouting.Choose(routes,"cable",""))==2);});
Check("missing saved cable is retained without substituting another output",()=>{var routes=OutputRouting.Choices([new("other","CABLE Input (VB-Audio Virtual Cable)",false,false)],"gone","missing","driver","local");var selected=OutputRouting.Choose(routes,"cable","gone");Assert(selected.Id=="gone"&&!selected.Available&&OutputRouting.EffectiveKind(selected)==0);});
Check("missing cable starts local and recovers the exact endpoint on refresh",()=>{var missing=OutputRouting.Choose(OutputRouting.Choices([],"saved","missing","driver","local"),"cable","saved");var back=OutputRouting.Choose(OutputRouting.Choices([new("saved","CABLE Input",false,false)],"saved","missing","driver","local"),"cable","saved");Assert(!missing.Available&&back.Available&&OutputRouting.EffectiveKind(back)==2);});
Check("explicit driver and local choices do not use a stored cable ID",()=>{var routes=OutputRouting.Choices([],"saved","missing","driver","local");Assert(OutputRouting.EffectiveKind(OutputRouting.Choose(routes,"driver","saved"))==1&&OutputRouting.EffectiveKind(OutputRouting.Choose(routes,"local","saved"))==0);});
Check("legacy state enables VB-CABLE while retaining presets calibration and output ID",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"{\"OutputId\":\"old-cable\",\"ActiveProfile\":\"podcast\",\"Settings\":{\"TargetDb\":-18}}");var store=new UserStore(root);var s=store.Load();Assert(!store.LoadWarning&&s.OutputMode=="cable"&&s.OutputId=="old-cable"&&s.ActiveProfile=="podcast"&&s.Settings.TargetDb==-18);}finally{Directory.Delete(root,true);}});
Check("output choice roundtrips without changing voice settings",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);var state=new UserState{OutputMode="local",OutputId="saved",Settings=new(){TargetDb=-18}};store.Save(state);var copy=store.Load();Assert(copy.OutputMode=="local"&&copy.OutputId=="saved"&&copy.Settings.TargetDb==-18);}finally{Directory.Delete(root,true);}});
Check("unknown output modes fail closed",()=>{Reject(()=>OutputRouting.ValidateMode("speaker"));Reject(()=>new UserStore(Path.GetTempPath()).Save(new UserState{OutputMode="anything"}));});
Check("corrupt output state recovers locally without enabling cable transmission",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{var store=new UserStore(root);foreach(string json in new[]{"{\"OutputMode\":\"invalid\",\"OutputId\":\"saved\"}","{broken"}){File.WriteAllText(Path.Combine(root,"state.json"),json);Assert(store.Load().OutputMode=="local"&&store.LoadWarning&&File.ReadAllText(Path.Combine(root,"state.json"))==json);}}finally{Directory.Delete(root,true);}});
Check("disconnected running cable is re-enumerated and deferred recovery stays pending",()=>{var available=new OutputRoute("cable","saved","CABLE Input");Assert(!OutputRouting.NeedsRefresh(available,2,1));Assert(OutputRouting.NeedsRefresh(available,2,0));Assert(OutputRouting.NeedsRefresh(available,0,1));Assert(OutputRouting.NeedsRefresh(available with{Available=false},0,1));Assert(!OutputRouting.NeedsRefresh(new("local","","local"),0,0));});
Check("cable output cannot be its own source even while cable is missing",()=>{var source=new AudioDevice("source","CABLE Output (VB-Audio Virtual Cable)",true,false);Assert(!OutputRouting.CanUseInput(source,new("cable","destination","CABLE Input")));Assert(!OutputRouting.CanUseInput(source,new("cable","destination","missing",false)));Assert(OutputRouting.CanUseInput(new("mic","USB mic",true,false),new("cable","destination","CABLE Input")));Assert(OutputRouting.CanUseInput(source,new("local","","local")));});
Check("unknown cable source waits for metadata before transmission and cannot bypass feedback rejection on return",()=>{var route=new OutputRoute("cable","destination","CABLE Input");Assert(!OutputRouting.CanUseInput(null,route));Assert(!OutputRouting.CanUseInput(new("saved","CABLE Output",true,false),route));Assert(OutputRouting.CanUseInput(new("saved","USB microphone",true,false),route));Assert(OutputRouting.CanUseInput(null,new("local","","local")));});
Check("talk modes preserve manual mute and fail closed before first key press",()=>{Assert(ShortcutSettings.Muted(1,false,false));Assert(!ShortcutSettings.Muted(1,true,false));Assert(ShortcutSettings.Muted(1,true,true));Assert(ShortcutSettings.Muted(2,true,false));Assert(!ShortcutSettings.Muted(2,false,false));Assert(!ShortcutSettings.Muted(0,false,false));Assert(ShortcutSettings.Muted(0,true,true));});
Check("shortcut plans validate collisions and retain fixed factory identifiers",()=>{Reject(()=>new ShortcutSettings(TalkMode:3).Validate());Reject(()=>new ShortcutSettings(TalkMode:1,HoldKey:"M").Validate());Reject(()=>new ShortcutSettings(HoldKey:"F12").Validate());var bindings=new ShortcutSettings(PresetKeys:true).Bindings();Assert(bindings['1']=="natural"&&bindings['5']=="podcast"&&bindings.Count==7);Assert(new ShortcutSettings().Bindings().Count==2);});
Check("hotkey conflicts roll back new reservations without losing old bindings",()=>{var registered=new Dictionary<int,int>();var released=new List<int>();int conflict=-1;using var registry=new HotkeyRegistry((id,key)=>{if(key==conflict)return false;registered.Add(id,key);return true;},id=>{released.Add(id);registered.Remove(id);});Assert(registry.Apply(new()));var old=registered.ToDictionary(x=>x.Key,x=>x.Value);conflict='Z';Assert(!registry.Apply(new("X","Z",1,"T",true)));Assert(registered.Count==2&&old.All(x=>registered[x.Key]==x.Value));Assert(registry.ActionFor(old.Single(x=>x.Value=='M').Key)=="mute");Assert(released.Count==1);});
Check("hotkey reconfiguration reuses chords atomically and unregisters removed chords",()=>{var registered=new Dictionary<int,int>();using var registry=new HotkeyRegistry((id,key)=>{Assert(!registered.ContainsValue(key));registered.Add(id,key);return true;},id=>registered.Remove(id));Assert(registry.Apply(new(PresetKeys:true)));Assert(registry.Apply(new("B","M",2,"T")));Assert(registered.Count==3);Assert(registry.ActionFor(registered.Single(x=>x.Value=='B').Key)=="mute");Assert(registry.ActionFor(registered.Single(x=>x.Value=='M').Key)=="bypass");for(int i=0;i<100;i++)Assert(registry.Apply(new(i%2==0?"X":"Y","B")));Assert(registered.Count==2);registry.Dispose();Assert(registered.Count==0);});
Check("shortcut state persists modes without recording transient held state or sharing keys",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));try{var store=new UserStore(root);store.Save(new UserState{TalkMode=1,HoldKey="K",PresetKeysEnabled=true});var copy=store.Load();Assert(copy.TalkMode==1&&copy.HoldKey=="K"&&copy.PresetKeysEnabled);Assert(!Profiles.Serialize(Profiles.Factory()[0]).Contains("holdKey",StringComparison.OrdinalIgnoreCase));}finally{Directory.Delete(root,true);}});
Check("old saved settings keep open mic and optional features disabled",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"{}");var store=new UserStore(root);var copy=store.Load();Assert(!store.LoadWarning&&copy.TalkMode==0&&!copy.PresetKeysEnabled&&copy.HoldKey=="T");}finally{Directory.Delete(root,true);}});
Check("invalid saved talk controls recover locally without transmitting",()=>{var root=Path.Combine(Path.GetTempPath(),"SES-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{File.WriteAllText(Path.Combine(root,"state.json"),"{\"TalkMode\":99}");var store=new UserStore(root);Assert(store.Load().OutputMode=="local"&&store.LoadWarning);}finally{Directory.Delete(root,true);}});
Check("advanced sensitivity profiles roundtrip and reject unsafe values",()=>{var profile=Profiles.Factory()[0];profile.Settings.SensitivityMode=1;profile.Settings.SensitivityAttackMs=5;profile.Settings.SensitivityHoldMs=200;profile.Settings.SensitivityReleaseMs=180;profile.Settings.SensitivityHysteresisDb=4;profile.Settings.SensitivityRatio=3;profile.Settings.SensitivityMaxReductionDb=30;var copy=Profiles.Deserialize(Profiles.Serialize(profile));Assert(copy.Settings.SensitivityMode==1&&copy.Settings.SensitivityRatio==3&&copy.Settings.SensitivityMaxReductionDb==30);Reject(()=>new AudioSettings{SensitivityMode=2}.Validate());Reject(()=>new AudioSettings{SensitivityHoldMs=float.PositiveInfinity}.Validate());Reject(()=>new AudioSettings{SensitivityAttackMs=0}.Validate());Reject(()=>new AudioSettings{SensitivityRatio=9}.Validate());});
Check("legacy profiles retain original gate timing defaults",()=>{var settings=Profiles.Deserialize("{\"schemaVersion\":1,\"name\":\"Legacy\",\"settings\":{}}").Settings;Assert(settings.SensitivityMode==0&&settings.SensitivityAttackMs==2&&settings.SensitivityHoldMs==300&&settings.SensitivityReleaseMs==120&&settings.SensitivityHysteresisDb==6);});
Check("strong noise cleaning removes dry mix while preserving personal tone and gain",()=>{var source=Profiles.Factory()[2].Settings;source.NoiseEnabled=false;source.NoiseAutoEnabled=true;source.NoiseMix=.65f;source.TargetDb=-18;source.MaxGainDb=9;var cleaned=NoiseControl.Strong(source);Assert(cleaned.NoiseEnabled&&!cleaned.NoiseAutoEnabled&&cleaned.NoiseMix==1&&cleaned.SensitivityEnabled&&cleaned.SensitivityAutoEnabled&&cleaned.SensitivityMode==1);Assert(cleaned.TargetDb==-18&&cleaned.MaxGainDb==9&&cleaned.Bands[0].GainDb==2&&source.NoiseMix==.65f&&!source.NoiseEnabled);cleaned.Bands[0].GainDb=0;Assert(source.Bands[0].GainDb==2);});
Check("strong noise cleaned profile roundtrips and rejects invalid source",()=>{var p=Profiles.Factory()[0];p.Settings=NoiseControl.Strong(p.Settings);var copy=Profiles.Deserialize(Profiles.Serialize(p));Assert(copy.Settings.NoiseMix==1&&copy.Settings.SensitivityMode==1&&copy.Settings.SensitivityMaxReductionDb==30);Reject(()=>NoiseControl.Strong(new(){TargetDb=float.NaN}));});
Check("game polling matches custom executable suffixes without changing exclusions",()=>{
    var policy=new GameModePolicy();
    Assert(policy.Update(true,new[]{new GameObservation("CustomGame")},new[]{"customgame.EXE"},0));
    Assert(policy.DetectedName=="CustomGame");
    policy.Update(false,Array.Empty<GameObservation>(),Array.Empty<string>(),1);
    Assert(!policy.Update(true,new[]{new GameObservation("chrome",true)},new[]{"customgame.EXE"},2));
    Assert(policy.Update(true,new[]{new GameObservation("chrome",true)},new[]{"Chrome.EXE"},3));
    Assert(!GameModePolicy.ValidProcessName(".hidden")&&!GameModePolicy.ValidProcessName("trailing ")&&!GameModePolicy.ValidProcessName("path/name"));
    Assert(GameModePolicy.ValidProcessName("Türkçe-Oyun_2.exe"));
});
Check("game span matcher preserves validation normalization precedence and first match",()=>{
    foreach(var name in new string?[]{null,"",".hidden","trailing ","path/name","path\\name","nul\0name",new('a',97)}){
        Assert(!GameModePolicy.ValidProcessName(name)&&!GameModePolicy.Matches(name.AsSpan(),true,Array.Empty<string>()));
    }
    foreach(string name in new[]{"a",new string('a',96),"Türkçe-Oyun_2.exe"})Assert(GameModePolicy.ValidProcessName(name)&&GameModePolicy.Matches(name.AsSpan(),true,Array.Empty<string>()));
    Assert(GameModePolicy.Matches("Cs2.EXE".AsSpan(),false,Array.Empty<string>()));
    Assert(!GameModePolicy.Matches("Chrome.EXE".AsSpan(),true,Array.Empty<string>()));
    Assert(GameModePolicy.Matches("Chrome.EXE".AsSpan(),false,new[]{"chrome"}));
    var policy=new GameModePolicy();
    Assert(policy.Update(true,new[]{new GameObservation("chrome",true),new GameObservation("FirstGame.exe"),new GameObservation("cs2")},new[]{"firstgame"},0));
    Assert(policy.DetectedName=="FirstGame");
    GameModePolicy.ValidateNames(new(){new('a',96),"Türkçe-Oyun_2.exe"});
    Reject(()=>GameModePolicy.ValidateNames(new(){new('a',97)}));Reject(()=>GameModePolicy.ValidateNames(new(){"nul\0name"}));
});
Check("game unmatched span polling does not allocate process-name strings",()=>{
    var custom=new[]{"CustomGame.EXE"};
    for(int i=0;i<100;i++)Assert(!GameModePolicy.Matches("NormalBackground.exe".AsSpan(),false,custom));
    long before=GC.GetAllocatedBytesForCurrentThread();bool matched=false;
    for(int i=0;i<10000;i++)matched|=GameModePolicy.Matches("NormalBackground.exe".AsSpan(),false,custom);
    long allocated=GC.GetAllocatedBytesForCurrentThread()-before;
    Assert(!matched&&allocated==0);
});
Console.WriteLine($"{checks} tests, {failures} failures");return failures==0?0:1;
